name: Release Rulesfile

on:
  push:
    tags:
      # potential semver
      - '[a-z]*[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release-rulesfile:
    runs-on: ubuntu-latest
    
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Rules
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Build registry artifact tool
        working-directory: build/registry
        run: go build -o rules-registry ./...

      - name: Get lowercase OCI repo prefix
        run: |
          echo "OCI_REPO_PREFIX=ghcr.io/${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Upload OCI artifacts to GitHub packages
        env:
          REGISTRY_USER: ${{ github.repository_owner }}
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
        run: build/registry/rules-registry push-to-oci registry.yaml ${{github.ref_name}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Upload OCI artifacts to S3
        env:
          AWS_S3_BUCKET: dig.lookslegit.org
          AWS_S3_PREFIX: rules
          AWS_S3_REGION: us-east-1
        run: build/registry/rules-registry upload-to-s3 registry.yaml ${{ github.ref_name }}
